### ISSUE TITLE
环境配置？

### ISSUE THREAD

**Issue by z3plus2** [chungkwong/mathocr-tap#2]
想请问下环境配置是啥，python3？ theano版本是多少，cuda几呀？

**Comment by chungkwong** [comment]
Python 3.7.8，Theano 1.0.5，Cuda 9.2。虽然笔划提取方法本身可以在CROHME系列数据集上达到70%+的准确率（细节属于商业机密，暂时不能公开），不过这个仓库的模型结构和数据有点过时，未能反映过去两年来公式识别领域的进展，放在现在已经缺乏竞争力。
